// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: httpresp.proto

#include "httpresp.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace lysutil {
namespace httpresp {
PROTOBUF_CONSTEXPR getTopicListResp::getTopicListResp(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.topic_list_)*/{}
  , /*decltype(_impl_.msg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.error_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct getTopicListRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR getTopicListRespDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~getTopicListRespDefaultTypeInternal() {}
  union {
    getTopicListResp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 getTopicListRespDefaultTypeInternal _getTopicListResp_default_instance_;
}  // namespace httpresp
}  // namespace lysutil
static ::_pb::Metadata file_level_metadata_httpresp_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_httpresp_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_httpresp_2eproto = nullptr;

const uint32_t TableStruct_httpresp_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::lysutil::httpresp::getTopicListResp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lysutil::httpresp::getTopicListResp, _impl_.error_),
  PROTOBUF_FIELD_OFFSET(::lysutil::httpresp::getTopicListResp, _impl_.msg_),
  PROTOBUF_FIELD_OFFSET(::lysutil::httpresp::getTopicListResp, _impl_.topic_list_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::lysutil::httpresp::getTopicListResp)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::lysutil::httpresp::_getTopicListResp_default_instance_._instance,
};

const char descriptor_table_protodef_httpresp_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016httpresp.proto\022\020lysutil.httpresp\"B\n\020ge"
  "tTopicListResp\022\r\n\005error\030\001 \001(\004\022\013\n\003msg\030\002 \001"
  "(\t\022\022\n\ntopic_list\030\003 \003(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_httpresp_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_httpresp_2eproto = {
    false, false, 110, descriptor_table_protodef_httpresp_2eproto,
    "httpresp.proto",
    &descriptor_table_httpresp_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_httpresp_2eproto::offsets,
    file_level_metadata_httpresp_2eproto, file_level_enum_descriptors_httpresp_2eproto,
    file_level_service_descriptors_httpresp_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_httpresp_2eproto_getter() {
  return &descriptor_table_httpresp_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_httpresp_2eproto(&descriptor_table_httpresp_2eproto);
namespace lysutil {
namespace httpresp {

// ===================================================================

class getTopicListResp::_Internal {
 public:
};

getTopicListResp::getTopicListResp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:lysutil.httpresp.getTopicListResp)
}
getTopicListResp::getTopicListResp(const getTopicListResp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  getTopicListResp* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.topic_list_){from._impl_.topic_list_}
    , decltype(_impl_.msg_){}
    , decltype(_impl_.error_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.msg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.msg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_msg().empty()) {
    _this->_impl_.msg_.Set(from._internal_msg(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.error_ = from._impl_.error_;
  // @@protoc_insertion_point(copy_constructor:lysutil.httpresp.getTopicListResp)
}

inline void getTopicListResp::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.topic_list_){arena}
    , decltype(_impl_.msg_){}
    , decltype(_impl_.error_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.msg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.msg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

getTopicListResp::~getTopicListResp() {
  // @@protoc_insertion_point(destructor:lysutil.httpresp.getTopicListResp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void getTopicListResp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.topic_list_.~RepeatedPtrField();
  _impl_.msg_.Destroy();
}

void getTopicListResp::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void getTopicListResp::Clear() {
// @@protoc_insertion_point(message_clear_start:lysutil.httpresp.getTopicListResp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.topic_list_.Clear();
  _impl_.msg_.ClearToEmpty();
  _impl_.error_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* getTopicListResp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 error = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.error_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string msg = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_msg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lysutil.httpresp.getTopicListResp.msg"));
        } else
          goto handle_unusual;
        continue;
      // repeated string topic_list = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_topic_list();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "lysutil.httpresp.getTopicListResp.topic_list"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* getTopicListResp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lysutil.httpresp.getTopicListResp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 error = 1;
  if (this->_internal_error() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_error(), target);
  }

  // string msg = 2;
  if (!this->_internal_msg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_msg().data(), static_cast<int>(this->_internal_msg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lysutil.httpresp.getTopicListResp.msg");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_msg(), target);
  }

  // repeated string topic_list = 3;
  for (int i = 0, n = this->_internal_topic_list_size(); i < n; i++) {
    const auto& s = this->_internal_topic_list(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lysutil.httpresp.getTopicListResp.topic_list");
    target = stream->WriteString(3, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lysutil.httpresp.getTopicListResp)
  return target;
}

size_t getTopicListResp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lysutil.httpresp.getTopicListResp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string topic_list = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.topic_list_.size());
  for (int i = 0, n = _impl_.topic_list_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.topic_list_.Get(i));
  }

  // string msg = 2;
  if (!this->_internal_msg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_msg());
  }

  // uint64 error = 1;
  if (this->_internal_error() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_error());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData getTopicListResp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    getTopicListResp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*getTopicListResp::GetClassData() const { return &_class_data_; }


void getTopicListResp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<getTopicListResp*>(&to_msg);
  auto& from = static_cast<const getTopicListResp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lysutil.httpresp.getTopicListResp)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.topic_list_.MergeFrom(from._impl_.topic_list_);
  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  if (from._internal_error() != 0) {
    _this->_internal_set_error(from._internal_error());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void getTopicListResp::CopyFrom(const getTopicListResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lysutil.httpresp.getTopicListResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool getTopicListResp::IsInitialized() const {
  return true;
}

void getTopicListResp::InternalSwap(getTopicListResp* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.topic_list_.InternalSwap(&other->_impl_.topic_list_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.msg_, lhs_arena,
      &other->_impl_.msg_, rhs_arena
  );
  swap(_impl_.error_, other->_impl_.error_);
}

::PROTOBUF_NAMESPACE_ID::Metadata getTopicListResp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_httpresp_2eproto_getter, &descriptor_table_httpresp_2eproto_once,
      file_level_metadata_httpresp_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace httpresp
}  // namespace lysutil
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::lysutil::httpresp::getTopicListResp*
Arena::CreateMaybeMessage< ::lysutil::httpresp::getTopicListResp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lysutil::httpresp::getTopicListResp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
