[http]
port = 8080
static_dir = "static"

[thread]
worker_count = 32
max_pending_count = 4

[topic]
topic_list = [
    "break_rx",
    "camera_rtk_bundle",
    "center_128_lidar_difop_data",
    "center_128_lidar_scan_data",
    "chassis_rx",
    "control_output",
    "data_info",
    "data_shaping_output",
    "front_fisheye_camera_record",
    "fusion_obstacle",
    "fusion_parkspace",
    "fusion_uss",
    "gear_rx",
    "hmi_data",
    "hut_data",
    "ivi_data",
    "lat_ctrl_data",
    "left_fisheye_camera_record",
    "light_rx",
    "localization_output",
    "lonc_ctrl_data",
    "mcudtc_data",
    "miscell_rx",
    "monitor_data",
    "motor_rx",
    "parking_fsm_output",
    "perception_camera",
    "perception_focus",
    "perception_lidar",
    "perception_view",
    "planning_output",
    "power_ack_data",
    "rear_fisheye_camera_record",
    "right_fisheye_camera_record",
    "rtk_data",
    "rtk_loc",
    "steer_rx",
    "throttle_rx",
    "time_sync_check_data",
    "tire_pressure_data",
    "uss_proc_data",
    "vehicle_angular_rates_data",
    "vehicleaccel_rx",
    "vehiclespeed_rx",
    "vehinfo_data",
    "version_info",
    "wheelspeed_rx"
]